# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: zephyrproject-rtos

  self:
    path: lcc-tortoise

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 3568e1b6d5cdd51a6b964a2a1d6d29200fea2056
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis_6      # required by the ARM port
          - hal_stm32  # required by the nucleo_f302r8 board (STM32 based)
    - name: mcuboot
      revision: eecc3f7dab98fee2be213f7b6519a4ad37a65688
      path: bootloader/mcuboot
      groups:
        - bootloader
    - name: mbedtls
      revision: be1dd5b11d8f59af0ab0995985e348a429999013
      path: modules/crypto/mbedtls
      groups:
        - crypto
